import fs from 'node:fs';
import { getLevels, validateLevel, assembleLevel, CHAPTER_UNLOCK_RATIO, CHAPTER_TWO_STAR_GATE, chapterUnlockThreshold } from '../src/levels.js';
import { TUNING, DIFFICULTIES, detectionRadius } from '../src/config.js';
import { createRunState, stepRun } from '../src/sim.js';

const results=[];const test=(name,fn)=>{try{fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.message});}};const assert=(v,msg)=>{if(!v)throw new Error(msg)};const close=(a,b,e=1e-9)=>Math.abs(a-b)<=e;
const levels=getLevels();
test('V1 content has 2 chapters / 7 levels',()=>{assert(levels.length===7,`levels=${levels.length}`);assert(new Set(levels.map(l=>l.chapter)).size===2,'missing chapter');});
test('all deterministic levels validate',()=>{for(const l of levels){const v=validateLevel(l);assert(v.ok,`${l.id}: ${v.errors.join(', ')}`);}});
test('each theme exposes at least 12 set pieces',()=>{for(const l of [levels[0],levels.at(-1)])assert(assembleLevel(l).pieces.length>=12,`${l.theme} pieces`);});
test('fixed simulation is 50Hz and debt is capped',()=>{assert(close(TUNING.fixedDt,.02),'fixed dt');assert(TUNING.maxDebtSteps===5,'debt cap');});
test('difficulty tier names and multipliers match spec',()=>{assert(JSON.stringify(Object.keys(DIFFICULTIES))==='["kitten","cat","alley"]','tier ids');const expected={kitten:[.80,.50,.50,.85,1.35,1.40,4],cat:[1,1,1,1,1,1,6],alley:[1.12,1.30,1.30,1.15,.85,.80,8]};for(const [id,e] of Object.entries(expected)){const t=DIFFICULTIES[id],actual=[t.henleySpeed,t.elapsed,t.escalation,t.detection,t.deadline,t.distraction,t.penalty];assert(actual.every((v,i)=>close(v,e[i])),`${id}: ${actual.join(',')}`);}});
test('dynamic detection D follows 8.2 + min(2, elapsed*0.018)',()=>{assert(close(detectionRadius(0,'cat'),8.2),`cat D0=${detectionRadius(0,'cat')}`);assert(close(detectionRadius(200,'cat'),10.2),`cat D200=${detectionRadius(200,'cat')}`);assert(close(detectionRadius(0,'kitten'),8.2*.85),`kitten D=${detectionRadius(0,'kitten')}`);assert(close(detectionRadius(0,'alley'),8.2*1.15),`alley D=${detectionRadius(0,'alley')}`);});
test('catch geometry is difficulty invariant',()=>{assert(TUNING.henley.catchDistance===.72,'catch distance');assert(TUNING.henley.catchHeight===.18,'catch height');assert(TUNING.henley.catchTime===.15,'catch timer');});
test('Henley spawn is at least base D from both cats',()=>{for(const l of levels){const w=assembleLevel(l);for(const c of w.spawn.cats){const d=Math.hypot(w.spawn.henley.x-c.x,w.spawn.henley.z-c.z);assert(d>=TUNING.henley.detectionBase,`${l.id}: ${d.toFixed(2)} < ${TUNING.henley.detectionBase}`);}}});
test('Cat tier optimal straight-line speed remains escapable at gameplay horizon',()=>{const elapsed=60,nearMisses=5,objectiveIndex=5,t=DIFFICULTIES.cat;const h=TUNING.henley.baseSpeed*t.henleySpeed+Math.min(1.05,elapsed*.0058)*t.elapsed+Math.min(.30,nearMisses*.018)*t.escalation+Math.min(.42,objectiveIndex*.045)*t.escalation;assert(TUNING.cat.maxSpeed>h,`cat ${TUNING.cat.maxSpeed} <= Henley ${h.toFixed(3)}`);});
test('chapter two gate is derived from 0.5 prior-chapter star ratio',()=>{const count=levels.filter(l=>l.chapter===1).length;assert(CHAPTER_UNLOCK_RATIO===.5,`ratio=${CHAPTER_UNLOCK_RATIO}`);assert(CHAPTER_TWO_STAR_GATE===Math.ceil(count*3*.5),`gate=${CHAPTER_TWO_STAR_GATE}`);assert(chapterUnlockThreshold(1)===CHAPTER_TWO_STAR_GATE,'threshold function drift');});
test('objective formula combo and miss tracking are retained',()=>{const l=levels[0],w=assembleLevel(l),s=createRunState(l,w,'kitten');s.cats[0].x=l.objectives[0].x;s.cats[0].z=l.objectives[0].z;const time=s.objectiveTime;stepRun(s,l,w,{steerDirection:{x:0,z:0},steerMagnitude:0,jump:false,switchCat:false},TUNING.fixedDt,{});const expected=Math.round((100+(time-TUNING.fixedDt)*9)*1);assert(s.pillars.objective===expected,`expected ${expected}, got ${s.pillars.objective}`);assert(s.activeTime[0]>0,'active time not tracked');});
test('versioned profile and legacy migration keys are present',()=>{const src=fs.readFileSync(new URL('../src/profile.js',import.meta.url),'utf8');for(const token of ["potr-save-v1","potr-best-040","potr-mischief-best-070","profileId","bestTime","bestScore","unlockedSets","lifetime"])assert(src.includes(token),`missing ${token}`);});
test('achievement catalogue contains all nine spec achievements',()=>{const profile=fs.readFileSync(new URL('../src/profile.js',import.meta.url),'utf8'),game=fs.readFileSync(new URL('../src/game.js',import.meta.url),'utf8');for(const id of ['cleanSweep','chainReaction','magpie','whiskers','untouchable','tagTeam','doubleTrouble','starCatcher','houseCats'])assert(profile.includes(id)&&game.includes(id),`missing ${id}`);});
test('touch UI has no permanent joystick/button cluster',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8')+fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');assert(!/joystick/i.test(html),'joystick found');});
test('runtime source has no third-party http imports',()=>{const files=fs.readdirSync(new URL('../src/',import.meta.url)).filter(f=>f.endsWith('.js'));for(const f of files){const s=fs.readFileSync(new URL(`../src/${f}`,import.meta.url),'utf8');assert(!/https?:\/\//.test(s),`${f} contains remote URL`);}});

for(const r of results)console.log(`${r.ok?'PASS':'FAIL'} ${r.name}${r.error?` — ${r.error}`:''}`);const failures=results.filter(r=>!r.ok);console.log(`\n${results.length-failures.length}/${results.length} contracts passing`);if(failures.length)process.exit(1);
