(() => {
  'use strict';
  const KEY = 'decision-ledger.records.v1';
  const statuses = ['Proposed', 'Accepted', 'Superseded'];
  let records = load();
  let editingId = null;
  const $ = id => document.getElementById(id);
  const list = $('decisionList'), empty = $('emptyState'), dialog = $('editorDialog'), form = $('decisionForm');
  const uid = () => (crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2));
  function load() { try { const value = JSON.parse(localStorage.getItem(KEY) || '[]'); return Array.isArray(value) ? value.filter(valid) : []; } catch { return []; } }
  function valid(r) { return r && typeof r === 'object' && typeof r.id === 'string' && typeof r.title === 'string' && statuses.includes(r.status); }
  function save() { localStorage.setItem(KEY, JSON.stringify(records)); }
  function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
  function dateText(value) { if (!value) return 'No decision date'; const d = new Date(value + 'T00:00:00'); return Number.isNaN(d.valueOf()) ? 'No decision date' : d.toLocaleDateString(undefined, {year:'numeric', month:'short', day:'numeric'}); }
  function render() {
    const query = $('search').value.trim().toLowerCase(), status = $('statusFilter').value, tag = $('tagFilter').value, order = $('sortOrder').value;
    const tags = [...new Set(records.flatMap(r => r.tags || []))].sort((a,b) => a.localeCompare(b));
    const currentTag = tag; $('tagFilter').innerHTML = '<option value="all">All tags</option>' + tags.map(t => `<option value="${esc(t)}">${esc(t)}</option>`).join(''); $('tagFilter').value = tags.includes(currentTag) ? currentTag : 'all';
    let shown = records.filter(r => { const hay = [r.title,r.owner,r.context,r.finalDecision,r.options,(r.tags||[]).join(' ')].join(' ').toLowerCase(); return (!query || hay.includes(query)) && (status === 'all' || r.status === status) && (tag === 'all' || (r.tags||[]).includes(tag)); });
    shown.sort((a,b) => order === 'title' ? a.title.localeCompare(b.title) : order === 'date' ? (b.decisionDate||'').localeCompare(a.decisionDate||'') || a.title.localeCompare(b.title) : (b.updatedAt||'').localeCompare(a.updatedAt||'') || a.title.localeCompare(b.title));
    $('resultCount').textContent = `${shown.length} decision${shown.length === 1 ? '' : 's'}`; $('resultHint').textContent = records.length ? (shown.length === records.length ? 'Every record in your ledger' : 'Matching your current view') : 'Your ledger is ready when you are.';
    list.innerHTML = shown.map(card).join(''); list.hidden = !shown.length; empty.hidden = !!shown.length; $('emptyTitle').textContent = records.length ? 'Nothing matches' : 'No decisions yet'; $('emptyText').textContent = records.length ? 'Try a different search or filter, or clear your current view.' : 'Start a record to preserve the thinking behind your next important choice.'; $('emptyAction').textContent = records.length ? 'Clear filters' : 'Create your first decision';
  }
  function card(r) { const copy = r.finalDecision || r.context || 'No additional detail yet.'; return `<article class="card"><div class="card-top"><h3>${esc(r.title)}</h3><span class="status status-${r.status.toLowerCase()}" aria-label="Status: ${esc(r.status)}">${esc(r.status)}</span></div><p class="card-copy">${esc(copy)}</p><div class="tags">${(r.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="card-meta">${esc(dateText(r.decisionDate))}${r.owner ? ` · ${esc(r.owner)}` : ''}</div><div class="card-actions"><button class="text-button" data-edit="${esc(r.id)}" type="button">Edit</button><button class="text-button danger" data-delete="${esc(r.id)}" type="button">Delete</button></div></article>`; }
  function openEditor(record) { editingId = record?.id || null; $('dialogTitle').textContent = record ? 'Edit decision' : 'New decision'; $('formError').hidden = true; [...form.elements].forEach(el => { if (el.name) el.value = record ? (el.name === 'tags' ? (record.tags||[]).join(', ') : record[el.name] || '') : (el.name === 'status' ? 'Proposed' : el.name === 'decisionDate' ? new Date().toISOString().slice(0,10) : ''); }); dialog.showModal(); $('title').focus(); }
  function close() { dialog.close(); editingId = null; }
  $('newDecision').onclick = () => openEditor(); $('emptyAction').onclick = () => { if (records.length) { $('search').value=''; $('statusFilter').value='all'; $('tagFilter').value='all'; render(); } else openEditor(); }; $('closeDialog').onclick = close; $('cancelDialog').onclick = close;
  form.onsubmit = event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); if (!data.title.trim()) { $('formError').textContent = 'A title is required so this decision can be found later.'; $('formError').hidden = false; $('title').focus(); return; } const now = new Date().toISOString(); const record = { id: editingId || uid(), title:data.title.trim(), status:data.status, decisionDate:data.decisionDate, owner:data.owner.trim(), context:data.context.trim(), finalDecision:data.finalDecision.trim(), options:data.options.trim(), tags:data.tags.split(',').map(x=>x.trim()).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i), updatedAt:now }; if (editingId) records = records.map(r => r.id === editingId ? {...r,...record} : r); else records.push(record); save(); close(); render(); toast(editingId ? 'Decision updated' : 'Decision saved'); };
  list.onclick = event => { const edit = event.target.closest('[data-edit]'), del = event.target.closest('[data-delete]'); if (edit) openEditor(records.find(r=>r.id===edit.dataset.edit)); if (del) { const r=records.find(x=>x.id===del.dataset.delete); if (r && confirm(`Delete “${r.title}”? This cannot be undone.`)) { records=records.filter(x=>x.id!==r.id); save(); render(); toast('Decision deleted'); } } };
  ['search','statusFilter','tagFilter','sortOrder'].forEach(id => $(id).addEventListener('input', render));
  $('exportData').onclick = () => { const blob = new Blob([JSON.stringify({format:'decision-ledger',version:1,records}, null, 2)], {type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='decision-ledger.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),500); toast('Ledger exported'); };
  $('importData').onclick = () => $('fileInput').click(); $('fileInput').onchange = event => { const file=event.target.files[0]; if (!file) return; const reader=new FileReader(); reader.onload = () => { try { const data=JSON.parse(reader.result); const incoming=Array.isArray(data) ? data : data.records; if (!Array.isArray(incoming) || !incoming.length || incoming.some(r=>!valid(r))) throw Error(); if (!confirm(`Replace your ${records.length} existing decision${records.length===1?'':'s'} with ${incoming.length} imported record${incoming.length===1?'':'s'}?`)) return; records=incoming; save(); render(); toast('Ledger imported'); } catch { toast('Import failed: choose a valid Decision Ledger JSON file'); } finally { event.target.value=''; } }; reader.readAsText(file); };
  let toastTimer; function toast(message) { $('toast').textContent=message; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500); }
  render();
})();
