import * as THREE from 'three';
import { BUILD, TUNING, clamp, slewAngle, damp } from './config.js';
import { getLevels, getLevel, assembleLevel, validateLevel } from './levels.js';
import { InputController } from './input.js';
import { AudioBus } from './audio.js';
import { loadCharacter } from './models.js';
import { SceneView } from './scene.js';
import { createRunState, stepRun, snapshotRun, stateDistance } from './sim.js';

const ACHIEVEMENT_NAMES={
  cleanSweep:'Clean Sweep',chainReaction:'Chain Reaction',magpie:'Magpie',whiskers:'Whiskers',untouchable:'Untouchable',tagTeam:'Tag Team',doubleTrouble:'Double Trouble',starCatcher:'Star Catcher',houseCats:'House Cats'
};

export class PawsGame{
  constructor(canvas,ui,profile){
    this.canvas=canvas;this.ui=ui;this.profile=profile;this.view=new SceneView(canvas);this.audio=new AudioBus();this.level=null;this.world=null;this.state=null;this.models=[];this.henleyModel=null;this.camYaw=0;this.accumulator=0;this.lastTime=performance.now();this.running=true;this.qaErrors=[];this.modelReady=false;this.controlPrompt='pointer';this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.runPersisted=false;this.achievementQueue=[];this.achievementTimer=null;
    this.firstRun={introDone:false,switchGuided:false,captureGuided:false};this.onboarding=null;this.switchGuidance=null;this.captureGuideUntil=0;
    this.input=new InputController(canvas,{hitInactiveCat:(x,y)=>this.hitInactiveCat(x,y),onDeviceChange:d=>this.onDevice(d)});
    this.bindUI();this.installQA();this.modelsPromise=this.loadModels();this.ui.showTitle();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);addEventListener('resize',()=>this.onResize());
  }
  bindUI(){this.ui.on('play',()=>this.ui.showMap(getLevels()));this.ui.on('map',()=>{this.stopRun();this.ui.showMap(getLevels());});this.ui.on('chooseLevel',id=>{const l=getLevel(id);if(l)this.ui.showRunSetup(l);});this.ui.on('start',l=>this.startLevel(l));this.ui.on('resume',()=>this.resume());this.ui.on('restart',()=>this.restart());this.ui.on('retry',()=>this.restart());document.querySelector('#pause-button').onclick=()=>this.pause('player');}
  async loadModels(){const err=(label)=>(e)=>{this.qaErrors.push(`model:${label}:${e?.message||e}`);};const [orange,gray,henley]=await Promise.all([loadCharacter('/assets/models/cat-orange.gltf',{placeholderColor:0xff7a22,onError:err('orange')}),loadCharacter('/assets/models/cat-gray.gltf',{placeholderColor:0x92a4b5,onError:err('gray')}),loadCharacter('/assets/models/henley.gltf',{placeholderColor:0x8d614e,onError:err('henley')})]);this.models=[orange,gray];this.henleyModel=henley;for(const m of [...this.models,this.henleyModel]){m.group.visible=false;this.view.scene.add(m.group);}this.modelReady=true;}
  applyCosmetic(){const cosmetic=this.profile.data.cosmetic,color=cosmetic==='teal'?0x55a89c:cosmetic==='rust'?0xc95d3e:0xe4d6ba;for(const model of this.models){const socket=model.group.getObjectByName('socket_collar');if(!socket)continue;for(const c of [...socket.children])if(c.userData.cosmetic)socket.remove(c);const ring=new THREE.Mesh(new THREE.TorusGeometry(.17,.035,6,18),new THREE.MeshStandardMaterial({color,roughness:.52,metalness:.08}));ring.userData.cosmetic=true;ring.rotation.x=Math.PI/2;socket.add(ring);}}
  beginOnboarding(){const c=this.state.cats[this.state.activeCat];this.onboarding={phase:'steer',phaseTime:0,totalTime:0,startX:c.x,startZ:c.z,jumpSeen:false};this.state.onboardingPhase='steer';this.state.objectiveTimerPaused=true;this.state.objectivePauseReason='onboarding';this.state.henleyPaused=true;this.view.setObjective(null);this.ui.setObjectiveVisible(false);this.ui.setObjectiveHeld(false);this.ui.showGuidance('steer','Drag to move');}
  finishOnboarding(){if(!this.state||!this.onboarding)return;this.firstRun.introDone=true;this.onboarding=null;this.state.onboardingPhase=null;this.state.objectiveTimerPaused=false;this.state.objectivePauseReason=null;this.state.henleyPaused=false;this.ui.hideGuidance();this.ui.setObjectiveVisible(true);this.ui.setObjectiveHeld(false);const o=this.level.objectives[this.state.objectiveIndex];this.view.setObjective(o||null);if(o)this.ui.toast(o.label,1000);this.maybeStartSwitchGuidance();}
  updateOnboarding(dt,actions){if(!this.onboarding||!this.state)return;const ob=this.onboarding,c=this.state.cats[this.state.activeCat];ob.phaseTime+=dt;ob.totalTime+=dt;if(ob.phase==='steer'){const moved=Math.hypot(c.x-ob.startX,c.z-ob.startZ);if((moved>=.5&&ob.phaseTime>=.45)||ob.phaseTime>=3.4){ob.phase='jump';ob.phaseTime=0;this.state.onboardingPhase='jump';this.ui.showGuidance('jump','Tap to jump');}}
    else if(ob.phase==='jump'){if(actions.jump||!c.grounded||c.y>.05)ob.jumpSeen=true;if((ob.jumpSeen&&ob.phaseTime>=.35)||ob.phaseTime>=3.4||ob.totalTime>=8){this.finishOnboarding();}}
  }
  maybeStartSwitchGuidance(){if(!this.state||this.firstRun.switchGuided||this.state.mode!=='playing'||this.state.onboardingPhase)return;const o=this.level.objectives[this.state.objectiveIndex];if(!o)return;const target=this.state.cats.findIndex(c=>c.name===o.cat);if(target<0||target===this.state.activeCat||this.state.cats[target].captured)return;this.firstRun.switchGuided=true;this.switchGuidance={targetIndex:target,objectiveId:o.id};this.state.objectiveTimerPaused=true;this.state.objectivePauseReason='switch-guidance';this.ui.setObjectiveHeld(true);this.updateGuidance(performance.now());}
  clearSwitchGuidance(){if(!this.state)return;this.switchGuidance=null;if(this.state.objectivePauseReason==='switch-guidance'){this.state.objectiveTimerPaused=false;this.state.objectivePauseReason=null;}this.ui.setObjectiveHeld(false);this.ui.hideGuidance('switch');}
  projectCat(index){if(!this.state||!this.models[index])return null;const p=this.models[index].group.position.clone().add(new THREE.Vector3(0,.65,0)).project(this.view.camera);return{x:(p.x*.5+.5)*innerWidth,y:(-.5*p.y+.5)*innerHeight,visible:p.z>-1&&p.z<1&&Math.abs(p.x)<=1&&Math.abs(p.y)<=1};}
  updateGuidance(now=performance.now()){if(!this.state){this.ui.hideGuidance();return;}if(this.captureGuideUntil>now){this.ui.showGuidance('return','Keep running · teammate returns');return;}if(this.switchGuidance){const p=this.projectCat(this.switchGuidance.targetIndex);this.ui.showGuidance('switch','Tap the other cat',p?.visible?p:null);return;}if(this.onboarding){this.ui.showGuidance(this.onboarding.phase,this.onboarding.phase==='steer'?'Drag to move':'Tap to jump');return;}this.ui.hideGuidance();}
  async startLevel(level){await this.modelsPromise;const validation=validateLevel(level);if(!validation.ok){this.qaErrors.push(...validation.errors.map(e=>`level:${level.id}:${e}`));this.ui.toast('This route failed validation.');return;}await this.audio.unlock().catch(()=>{});this.audio.preload().catch(()=>{});this.input.resetTransient();this.runPersisted=false;this.switchGuidance=null;this.captureGuideUntil=0;this.level=level;this.world=assembleLevel(level);this.state=createRunState(level,this.world,this.profile.data.difficulty);this.view.build(level,this.world);this.accumulator=0;this.camYaw=this.state.cats[this.state.activeCat].heading;this.applyCosmetic();for(const m of this.models)m.group.visible=true;this.henleyModel.group.visible=true;this.syncModels(0);this.updateCamera(0,{snap:true});this.ui.startHUD();if(level.id==='ch1-l1'&&!this.firstRun.introDone)this.beginOnboarding();else{this.view.setObjective(level.objectives[0]);this.ui.setObjectiveVisible(true);this.ui.setObjectiveHeld(false);this.maybeStartSwitchGuidance();}this.updateHUD();}
  stopRun(){this.audio.stopAll();this.input.resetTransient();this.onboarding=null;this.switchGuidance=null;this.captureGuideUntil=0;this.ui.hideGuidance();this.state=null;this.level=null;this.world=null;for(const m of this.models)m.group.visible=false;if(this.henleyModel)this.henleyModel.group.visible=false;this.view.setObjective(null);}
  restart(){if(!this.level)return;const l=this.level;this.audio.stopAll();this.startLevel(l);}
  pause(reason='player'){if(!this.state||this.state.mode!=='playing'||this.state.paused)return;this.state.paused=true;this.state.pauseReason=reason;this.ui.setPause(true,{reason,resumeOnly:reason==='rotation'});}
  resume(){if(!this.state)return;this.input.resetTransient();this.state.paused=false;this.state.pauseReason='';this.lastTime=performance.now();this.accumulator=0;this.ui.setPause(false);}
  onResize(){this.view.resize();if(this.state?.mode==='playing'&&!this.state.paused&&matchMedia('(pointer:coarse)').matches)this.pause('rotation');}
  onDevice(d){this.controlPrompt=d;}
  hitInactiveCat(clientX,clientY){if(!this.state||!this.models.length)return false;const rect=this.canvas.getBoundingClientRect();this.pointer.x=((clientX-rect.left)/rect.width)*2-1;this.pointer.y=-((clientY-rect.top)/rect.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.view.camera);const inactive=1-this.state.activeCat;if(this.state.cats[inactive].captured)return false;return this.raycaster.intersectObject(this.models[inactive].group,true).length>0;}
  awardAchievement(id){if(!ACHIEVEMENT_NAMES[id]||!this.profile.markAchievement(id))return;this.achievementQueue.push(ACHIEVEMENT_NAMES[id]);this.flushAchievementQueue();}
  flushAchievementQueue(){if(this.achievementTimer||!this.achievementQueue.length)return;const name=this.achievementQueue.shift();this.ui.toast(`Achievement · ${name}`,1850);this.achievementTimer=setTimeout(()=>{this.achievementTimer=null;this.flushAchievementQueue();},1950);}
  evaluateRunAchievements(){if(!this.state||!this.level)return;const s=this.state;if(s.objectiveMisses===0)this.awardAchievement('cleanSweep');if(s.collected.size===this.world.collectibles.length)this.awardAchievement('magpie');if(s.autonomousCaptures===0)this.awardAchievement('untouchable');if(s.switchBonusObjectives.size===this.level.objectives.length)this.awardAchievement('tagTeam');const activeTotal=s.activeTime[0]+s.activeTime[1];if(activeTotal>0&&s.activeTime.every(t=>t/activeTotal>=.40))this.awardAchievement('doubleTrouble');if(s.successStars===3)this.awardAchievement('starCatcher');const chapterOne=getLevels().filter(l=>l.chapter===1);if(chapterOne.length&&chapterOne.every(l=>(this.profile.data.levels[l.id]?.stars||0)===3))this.awardAchievement('houseCats');}
  persistFailure(){if(this.runPersisted||!this.state)return;this.runPersisted=true;this.profile.recordFailedRun({autonomousCaptures:this.state.autonomousCaptures,score:this.state.score,collectibles:this.state.collected.size,nearMisses:this.state.nearMisses});}
  persistSuccess(){if(this.runPersisted||!this.state||!this.level)return;this.runPersisted=true;this.profile.record(this.level.id,{score:this.state.score,stars:this.state.successStars,elapsed:this.state.elapsed,difficulty:this.state.difficulty,metrics:{autonomousCaptures:this.state.autonomousCaptures,activeCaptures:0,collectibles:this.state.collected.size,nearMisses:this.state.nearMisses}});this.evaluateRunAchievements();}
  callbacks(){return {
    switchCat:()=>{this.audio.play('switch',{volume:.22});this.ui.toast(`Now controlling ${this.state.cats[this.state.activeCat].name==='orange'?'Orange':'Gray'}`,900);if(this.switchGuidance&&this.state.activeCat===this.switchGuidance.targetIndex)this.clearSwitchGuidance();},
    switchBonus:()=>this.ui.toast('Tag-team +40',900),
    jump:()=>this.audio.play('jump',{volume:.18}),vault:()=>this.audio.play('jump',{volume:.18,rate:1.08}),land:()=>this.audio.play('land',{volume:.16}),
    collect:c=>{this.audio.play('collect',{volume:.22});this.view.collect(c.id);if(this.state.collected.size===this.world.collectibles.length)this.awardAchievement('magpie');},
    objective:(o,pts,burst)=>{this.audio.play('objective',{volume:.3});this.audio.maybeCat('objective');this.ui.toast(`${o.label} +${pts}${burst?' · MISCHIEF BURST':''}`,1450);this.view.setObjective(this.level.objectives[this.state.objectiveIndex]||null);if(this.state.combo>=4)this.awardAchievement('chainReaction');this.maybeStartSwitchGuidance();},
    deadline:()=>this.ui.toast('Objective reset · combo lost',1200),
    nearMiss:()=>{this.audio.play('near',{volume:.26});this.ui.toast('Near miss +60',950);this.models[this.state.activeCat].play('nearCatch',{loop:false});if(this.state.nearMisses>=5)this.awardAchievement('whiskers');},
    autonomousCaught:(c,penalty)=>{this.audio.play('caught',{volume:.18,rate:1.15});this.ui.toast(`${c.name==='orange'?'Orange':'Gray'} caught · back in ${penalty.toFixed(0)}s`,1500);if(!this.firstRun.captureGuided){this.firstRun.captureGuided=true;this.captureGuideUntil=performance.now()+2600;this.updateGuidance();}},
    objectiveReassigned:(o,cat)=>this.ui.toast(`${o.label} reassigned to ${cat==='orange'?'Orange':'Gray'}`,1350),
    objectivePaused:()=>{this.ui.setObjectiveHeld(true);this.ui.toast('Teammate objective held',1000);},
    objectiveResumed:()=>{this.ui.setObjectiveHeld(false);this.ui.toast('Objective timer resumed',900);},
    autonomousReturned:()=>{this.audio.play('switch',{volume:.16,rate:.9});this.ui.toast('Your teammate is back',900);},
    henleyState:s=>{if(['windup','reach'].includes(s))this.audio.maybeCat('danger');},
    caught:()=>{this.audio.play('caught',{volume:.36});this.models[this.state.activeCat].play('caught',{loop:false});this.persistFailure();setTimeout(()=>this.ui.showCaught({score:this.state?.score||0}),180);},
    success:()=>{this.audio.play('success',{volume:.34});for(const m of this.models)m.play('success',{loop:false});this.persistSuccess();const {score,successStars:stars,pillars,elapsed}=this.state;setTimeout(()=>this.ui.showResults({level:this.level,score,stars,pillars,elapsed}),220);}
  };}
  step(dt,actions){if(!this.state)return;if(actions.pause){this.pause('player');return;}stepRun(this.state,this.level,this.world,actions,dt,this.callbacks());this.updateOnboarding(dt,actions);}
  syncModels(dt){if(!this.state||!this.modelReady)return;for(let i=0;i<2;i++){const c=this.state.cats[i],m=this.models[i];m.group.visible=!c.captured;m.group.position.set(c.x,c.y,c.z);m.group.rotation.y=c.heading+Math.PI;const speed=Math.hypot(c.vx,c.vz);let anim='idle';if(this.state.mode==='caught'&&i===this.state.activeCat)anim='caught';else if(c.vaultAnim>0)anim='jumpRise';else if(c.landTimer>0)anim='land';else if(!c.grounded)anim=c.vy>0?'jumpRise':'fall';else if(speed>3.1)anim='run';else if(speed>.5)anim='accelerate';m.play(anim,{loop:!['caught','land','success'].includes(anim)});m.update(dt);}const h=this.state.henley;this.henleyModel.group.position.set(h.x,h.y,h.z);this.henleyModel.group.rotation.y=h.heading+Math.PI;const ha=['windup','reach'].includes(h.state)?'alert':h.state==='pounce'?'run':h.state==='distracted'?'idle':'run';this.henleyModel.play(ha);this.henleyModel.update(dt);}
  updateCamera(dt,{snap=false}={}){if(!this.state)return;const camera=this.view.camera,cat=this.state.cats[this.state.activeCat],h=this.state.henley,o=this.state.onboardingPhase?null:this.level.objectives[this.state.objectiveIndex],hd=stateDistance(cat,h),portrait=camera.aspect<.8,close=hd<TUNING.camera.closeHenleyDistance&&!this.state.henleyPaused,pressure=close?clamp((TUNING.camera.closeHenleyDistance-hd)/6,0,1):0;let targetYaw=cat.heading;if(o){const oy=Math.atan2(o.x-cat.x,o.z-cat.z),d=Math.hypot(o.x-cat.x,o.z-cat.z),blend=Math.min(.42,Math.max(.08,1-d/14)*.38+.08);targetYaw=angleBlend(cat.heading,oy,blend);}if(close){const pursuitYaw=Math.atan2(h.x-cat.x,h.z-cat.z);targetYaw=angleBlend(targetYaw,pursuitYaw,.55+pressure*.25);}this.camYaw=snap?targetYaw:slewAngle(this.camYaw,targetYaw,TUNING.camera.yawRate*dt);const targetFov=portrait?(close?58:52):(close?52:48);const nextFov=snap?targetFov:damp(camera.fov,targetFov,4.5,dt);if(Math.abs(camera.fov-nextFov)>.001){camera.fov=nextFov;camera.updateProjectionMatrix();}const baseDist=portrait?9.0:TUNING.camera.distance+.25,baseHeight=portrait?5.2:TUNING.camera.height+.1,frameBoost=close?(portrait?3.5:1.8)*(.35+pressure*.65):0,focusBlend=close?.28+pressure*.14:0,focusX=cat.x+(h.x-cat.x)*focusBlend,focusZ=cat.z+(h.z-cat.z)*focusBlend,fx=Math.sin(this.camYaw),fz=Math.cos(this.camYaw),camDist=baseDist+frameBoost,desired={x:focusX-fx*camDist,y:baseHeight+frameBoost*(portrait?.22:.16),z:focusZ-fz*camDist};if(snap){camera.position.set(desired.x,desired.y,desired.z);}else{camera.position.x=damp(camera.position.x,desired.x,TUNING.camera.damping,dt);camera.position.y=damp(camera.position.y,desired.y,TUNING.camera.damping,dt);camera.position.z=damp(camera.position.z,desired.z,TUNING.camera.damping,dt);}const objectiveLead=o?Math.min(1.1,Math.hypot(o.x-cat.x,o.z-cat.z)*.05):0,lookAhead=(TUNING.camera.lookAhead+objectiveLead)*(close?.5:1);camera.lookAt(focusX+fx*lookAhead,.7+cat.y*.28,focusZ+fz*lookAhead);}
  updateHenleyIndicator(){const el=document.querySelector('#henley-indicator');if(!this.state||this.state.henleyPaused||!['chase','windup','pounce','reach'].includes(this.state.henley.state)){el.classList.add('hidden');return;}const p=new THREE.Vector3(this.state.henley.x,.8,this.state.henley.z).project(this.view.camera);if(p.z>-1&&p.z<1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.9){el.classList.add('hidden');return;}const x=Math.max(-.82,Math.min(.82,p.x)),y=Math.max(-.7,Math.min(.7,p.y));el.style.left=`${50+x*46}%`;el.style.top=`${50-y*42}%`;el.classList.remove('hidden');}
  updateHUD(){if(!this.state)return;const base=this.level.objectives[this.state.objectiveIndex],objective=this.state.onboardingPhase?null:(base?{...base,cat:this.state.objectiveCatOverride||base.cat}:null);this.ui.updateHUD({objective,timeLeft:this.state.objectiveTime,score:this.state.score,combo:this.state.combo,stars:this.state.successStars||0});this.ui.setObjectiveVisible(!this.state.onboardingPhase);this.ui.setObjectiveHeld(this.state.objectiveTimerPaused&&!this.state.onboardingPhase);const ripple=document.querySelector('#drag-ripple');const d=this.input.drag;if(d){ripple.style.left=`${d.x0}px`;ripple.style.top=`${d.y0}px`;ripple.classList.remove('hidden');}else ripple.classList.add('hidden');}
  frame(now){if(!this.running)return;const raw=Math.min(.1,(now-this.lastTime)/1000);this.lastTime=now;if(this.state&&!this.state.paused&&this.state.mode==='playing'){this.accumulator+=raw;let steps=0;let consumedTransient=false;let actions=this.input.sample(this.camYaw);while(this.accumulator>=TUNING.fixedDt&&steps<TUNING.maxDebtSteps){this.step(TUNING.fixedDt,actions);if(!consumedTransient){this.input.consumeTransient();consumedTransient=true;}actions={...actions,jump:false,switchCat:false,pause:false};this.accumulator-=TUNING.fixedDt;steps++;}if(steps===TUNING.maxDebtSteps&&this.accumulator>=TUNING.fixedDt)this.accumulator=0;this.syncModels(raw);this.updateCamera(raw);this.updateHUD();this.updateHenleyIndicator();this.updateGuidance(now);}else if(this.state){this.syncModels(raw);this.updateGuidance(now);}this.view.update(now/1000,raw);this.view.render();this.updateQA();requestAnimationFrame(this.frame);}
  updateQA(){if(!window.__PAWS_QA__)return;window.__PAWS_QA__.mode=this.state?.mode||'menu';window.__PAWS_QA__.paused=!!this.state?.paused;window.__PAWS_QA__.errors=this.qaErrors;window.__PAWS_QA__.drawCalls=this.view.renderer.info.render.calls;}
  installQA(){const q=new URLSearchParams(location.search).has('qa');window.__PAWS_QA__={mode:'menu',paused:false,errors:this.qaErrors,drawCalls:0,build:BUILD};window.__PAWS_GAME__={snapshot:()=>this.state?snapshotRun(this.state):null,pause:()=>this.pause('player'),resume:()=>this.resume(),restart:()=>this.restart(),teleportToObjective:()=>{if(!this.state)return;const o=this.level.objectives[this.state.objectiveIndex];if(o){const c=this.state.cats[this.state.activeCat];c.x=o.x;c.z=o.z;c.y=0;}},selectObjectiveCat:()=>{if(!this.state)return;const o=this.level.objectives[this.state.objectiveIndex];const target=this.state.objectiveCatOverride||o?.cat;const idx=this.state.cats.findIndex(c=>c.name===target);if(idx>=0&&!this.state.cats[idx].captured)this.state.activeCat=idx;},placeHenleyNear:(distance=.55)=>{if(!this.state)return;this.finishOnboarding();if(this.state.objectivePauseReason==='switch-guidance')this.clearSwitchGuidance();this.state.henleyPaused=false;const c=this.state.cats[this.state.activeCat],h=this.state.henley;h.x=c.x+distance;h.z=c.z;h.state='pounce';h.target=this.state.activeCat;h.lockedHeading=Math.atan2(c.x-h.x,c.z-h.z);h.timer=.35;h.catchTimer=0;},projectCat:index=>this.projectCat(index),framing:()=>{if(!this.state)return null;const project=(x,y,z)=>new THREE.Vector3(x,y,z).project(this.view.camera);const c=this.state.cats[this.state.activeCat],h=this.state.henley,cp=project(c.x,.65+c.y,c.z),hp=project(h.x,.8,h.z);const visible=p=>p.z>-1&&p.z<1&&Math.abs(p.x)<=1&&Math.abs(p.y)<=1;return{catVisible:visible(cp),henleyVisible:visible(hp),distance:stateDistance(c,h),indicatorVisible:!document.querySelector('#henley-indicator').classList.contains('hidden')};},completeOnboarding:()=>this.finishOnboarding(),completeRoute:()=>{if(!this.state)return;this.finishOnboarding();this.state.henley.distractionTimer=999;let guard=20;while(this.state.mode==='playing'&&guard--){if(this.state.objectivePauseReason==='switch-guidance')this.clearSwitchGuidance();const o=this.level.objectives[this.state.objectiveIndex];const target=this.state.objectiveCatOverride||o?.cat;const idx=this.state.cats.findIndex(c=>c.name===target&&!c.captured);if(idx<0)break;this.state.activeCat=idx;this.state.cats[idx].x=o.x;this.state.cats[idx].z=o.z;this.state.cats[idx].y=0;stepRun(this.state,this.level,this.world,{steerDirection:{x:0,z:0},steerMagnitude:0,jump:false,switchCat:false},TUNING.fixedDt,this.callbacks());}},setModeSnapshot:()=>this.updateQA()};window.addEventListener('error',e=>this.qaErrors.push(`error:${e.message}`));window.addEventListener('unhandledrejection',e=>this.qaErrors.push(`rejection:${e.reason?.message||e.reason}`));if(q){const btn=document.querySelector('#qa-indicator'),panel=document.querySelector('#qa-panel');btn.classList.remove('hidden');btn.onclick=()=>{panel.classList.toggle('hidden');panel.textContent=JSON.stringify({qa:window.__PAWS_QA__,state:this.state?snapshotRun(this.state):null},null,2);};}}
}
function angleBlend(a,b,t){return a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*t;}
