import * as THREE from 'three';
import { BUILD, TUNING, slewAngle, damp } from './config.js';
import { getLevels, getLevel, assembleLevel, validateLevel } from './levels.js';
import { InputController } from './input.js';
import { AudioBus } from './audio.js';
import { loadCharacter } from './models.js';
import { SceneView } from './scene.js';
import { createRunState, stepRun, snapshotRun, stateDistance } from './sim.js';

export class PawsGame{
  constructor(canvas,ui,profile){
    this.canvas=canvas;this.ui=ui;this.profile=profile;this.view=new SceneView(canvas);this.audio=new AudioBus();this.level=null;this.world=null;this.state=null;this.models=[];this.henleyModel=null;this.camYaw=Math.PI;this.accumulator=0;this.lastTime=performance.now();this.running=true;this.qaErrors=[];this.modelReady=false;this.controlPrompt='pointer';this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();
    this.input=new InputController(canvas,{hitInactiveCat:(x,y)=>this.hitInactiveCat(x,y),onDeviceChange:d=>this.onDevice(d)});
    this.bindUI();this.installQA();this.modelsPromise=this.loadModels();this.ui.showTitle();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);addEventListener('resize',()=>this.onResize());
  }
  bindUI(){this.ui.on('play',()=>this.ui.showMap(getLevels()));this.ui.on('map',()=>{this.stopRun();this.ui.showMap(getLevels());});this.ui.on('chooseLevel',id=>{const l=getLevel(id);if(l)this.ui.showRunSetup(l);});this.ui.on('start',l=>this.startLevel(l));this.ui.on('resume',()=>this.resume());this.ui.on('restart',()=>this.restart());this.ui.on('retry',()=>this.restart());document.querySelector('#pause-button').onclick=()=>this.pause('player');}
  async loadModels(){const err=(label)=>(e)=>{this.qaErrors.push(`model:${label}:${e?.message||e}`);};const [orange,gray,henley]=await Promise.all([loadCharacter('/assets/models/cat-orange.gltf',{placeholderColor:0xff7a22,onError:err('orange')}),loadCharacter('/assets/models/cat-gray.gltf',{placeholderColor:0x92a4b5,onError:err('gray')}),loadCharacter('/assets/models/henley.gltf',{placeholderColor:0x8d614e,onError:err('henley')})]);this.models=[orange,gray];this.henleyModel=henley;for(const m of [...this.models,this.henleyModel]){m.group.visible=false;this.view.scene.add(m.group);}this.modelReady=true;}
  applyCosmetic(){const cosmetic=this.profile.data.cosmetic,color=cosmetic==='teal'?0x55a89c:cosmetic==='rust'?0xc95d3e:0xe4d6ba;for(const model of this.models){const socket=model.group.getObjectByName('socket_collar');if(!socket)continue;for(const c of [...socket.children])if(c.userData.cosmetic)socket.remove(c);const ring=new THREE.Mesh(new THREE.TorusGeometry(.17,.035,6,18),new THREE.MeshStandardMaterial({color,roughness:.52,metalness:.08}));ring.userData.cosmetic=true;ring.rotation.x=Math.PI/2;socket.add(ring);}}
  async startLevel(level){await this.modelsPromise;const validation=validateLevel(level);if(!validation.ok){this.qaErrors.push(...validation.errors.map(e=>`level:${level.id}:${e}`));this.ui.toast('This route failed validation.');return;}await this.audio.unlock().catch(()=>{});this.audio.preload().catch(()=>{});this.input.resetTransient();this.level=level;this.world=assembleLevel(level);this.state=createRunState(level,this.world,this.profile.data.difficulty);this.view.build(level,this.world);this.view.setObjective(level.objectives[0]);this.accumulator=0;this.applyCosmetic();for(const m of this.models)m.group.visible=true;this.henleyModel.group.visible=true;this.syncModels(0);this.ui.startHUD();this.ui.toast('Drag to run · tap to jump',1700);this.updateHUD();}
  stopRun(){this.audio.stopAll();this.input.resetTransient();this.state=null;this.level=null;this.world=null;for(const m of this.models)m.group.visible=false;if(this.henleyModel)this.henleyModel.group.visible=false;this.view.setObjective(null);}
  restart(){if(!this.level)return;const l=this.level;this.audio.stopAll();this.startLevel(l);}
  pause(reason='player'){if(!this.state||this.state.mode!=='playing'||this.state.paused)return;this.state.paused=true;this.state.pauseReason=reason;this.ui.setPause(true,{reason,resumeOnly:reason==='rotation'});}
  resume(){if(!this.state)return;this.input.resetTransient();this.state.paused=false;this.state.pauseReason='';this.lastTime=performance.now();this.accumulator=0;this.ui.setPause(false);}
  onResize(){this.view.resize();if(this.state?.mode==='playing'&&!this.state.paused&&matchMedia('(pointer:coarse)').matches)this.pause('rotation');}
  onDevice(d){this.controlPrompt=d;}
  hitInactiveCat(clientX,clientY){if(!this.state||!this.models.length)return false;const rect=this.canvas.getBoundingClientRect();this.pointer.x=((clientX-rect.left)/rect.width)*2-1;this.pointer.y=-((clientY-rect.top)/rect.height)*2+1;this.raycaster.setFromCamera(this.pointer,this.view.camera);const inactive=1-this.state.activeCat;if(this.state.cats[inactive].captured)return false;return this.raycaster.intersectObject(this.models[inactive].group,true).length>0;}
  callbacks(){return {
    switchCat:()=>{this.audio.play('switch',{volume:.22});this.ui.toast(`Now controlling ${this.state.cats[this.state.activeCat].name==='orange'?'Orange':'Gray'}`,900);},
    switchBonus:()=>this.ui.toast('Tag-team +40',900),
    collect:c=>{this.audio.play('collect',{volume:.22});this.view.collect(c.id);},
    objective:(o,pts,burst)=>{this.audio.play('objective',{volume:.3});this.audio.maybeCat('objective');this.ui.toast(`${o.label} +${pts}${burst?' · MISCHIEF BURST':''}`,1450);this.view.setObjective(this.level.objectives[this.state.objectiveIndex]||null);},
    deadline:()=>this.ui.toast('Objective reset · combo lost',1200),
    nearMiss:()=>{this.audio.play('near',{volume:.26});this.ui.toast('Near miss +60',950);this.models[this.state.activeCat].play('nearCatch',{loop:false});},
    autonomousCaught:c=>{this.audio.play('caught',{volume:.18,rate:1.15});this.ui.toast(`${c.name==='orange'?'Orange':'Gray'} caught — returning soon`,1400);},
    autonomousReturned:()=>{this.audio.play('switch',{volume:.16,rate:.9});this.ui.toast('Your teammate is back',900);},
    henleyState:s=>{if(['windup','reach'].includes(s))this.audio.maybeCat('danger');},
    caught:()=>{this.audio.play('caught',{volume:.36});this.models[this.state.activeCat].play('caught',{loop:false});setTimeout(()=>this.ui.showCaught({score:this.state?.score||0}),180);},
    success:()=>{this.audio.play('success',{volume:.34});for(const m of this.models)m.play('success',{loop:false});const {score,successStars:stars,pillars,elapsed,tagTeam}=this.state;this.profile.record(this.level.id,{score,stars,tagTeam});setTimeout(()=>this.ui.showResults({level:this.level,score,stars,pillars,elapsed}),220);}
  };}
  step(dt,actions){if(!this.state)return;if(actions.pause){this.pause('player');return;}stepRun(this.state,this.level,this.world,actions,dt,this.callbacks());}
  syncModels(dt){if(!this.state||!this.modelReady)return;for(let i=0;i<2;i++){const c=this.state.cats[i],m=this.models[i];m.group.visible=!c.captured;m.group.position.set(c.x,c.y,c.z);m.group.rotation.y=c.heading+Math.PI;const speed=Math.hypot(c.vx,c.vz);let anim='idle';if(this.state.mode==='caught'&&i===this.state.activeCat)anim='caught';else if(!c.grounded)anim=c.vy>0?'jumpRise':'fall';else if(speed>3.1)anim='run';else if(speed>.5)anim='accelerate';m.play(anim,{loop:!['caught','land','success'].includes(anim)});m.update(dt);}const h=this.state.henley;this.henleyModel.group.position.set(h.x,h.y,h.z);this.henleyModel.group.rotation.y=h.heading+Math.PI;let ha=['windup','reach'].includes(h.state)?'alert':h.state==='pounce'?'run':h.state==='distracted'?'idle':'run';this.henleyModel.play(ha);this.henleyModel.update(dt);}
  updateCamera(dt){if(!this.state)return;const cat=this.state.cats[this.state.activeCat],o=this.level.objectives[this.state.objectiveIndex];let targetYaw=cat.heading;if(o){const oy=Math.atan2(o.x-cat.x,o.z-cat.z);const d=Math.hypot(o.x-cat.x,o.z-cat.z);const blend=Math.min(.42,Math.max(.08,1-d/14)*.38+.08);targetYaw=cat.heading+angleBlend(cat.heading,oy,blend);}this.camYaw=slewAngle(this.camYaw,targetYaw,TUNING.camera.yawRate*dt);const hd=stateDistance(cat,this.state.henley),extra=hd<TUNING.camera.closeHenleyDistance?(1-hd/TUNING.camera.closeHenleyDistance)*TUNING.camera.closeBoost:0,camDist=TUNING.camera.distance+extra;const fx=Math.sin(this.camYaw),fz=Math.cos(this.camYaw),desired={x:cat.x-fx*camDist,y:TUNING.camera.height+extra*.18,z:cat.z-fz*camDist};this.view.camera.position.x=damp(this.view.camera.position.x,desired.x,TUNING.camera.damping,dt);this.view.camera.position.y=damp(this.view.camera.position.y,desired.y,TUNING.camera.damping,dt);this.view.camera.position.z=damp(this.view.camera.position.z,desired.z,TUNING.camera.damping,dt);const lookAhead=TUNING.camera.lookAhead+(o?Math.min(1.1,Math.hypot(o.x-cat.x,o.z-cat.z)*.05):0);this.view.camera.lookAt(cat.x+fx*lookAhead,.65+cat.y*.35,cat.z+fz*lookAhead);}
  updateHenleyIndicator(){const el=document.querySelector('#henley-indicator');if(!this.state||!['chase','windup','pounce','reach'].includes(this.state.henley.state)){el.classList.add('hidden');return;}const p=new THREE.Vector3(this.state.henley.x,.8,this.state.henley.z).project(this.view.camera);if(p.z>-1&&p.z<1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.9){el.classList.add('hidden');return;}const x=Math.max(-.82,Math.min(.82,p.x)),y=Math.max(-.7,Math.min(.7,p.y));el.style.left=`${50+x*46}%`;el.style.top=`${50-y*42}%`;el.classList.remove('hidden');}
  updateHUD(){if(!this.state)return;this.ui.updateHUD({objective:this.level.objectives[this.state.objectiveIndex],timeLeft:this.state.objectiveTime,score:this.state.score,combo:this.state.combo,stars:this.state.successStars||0});const ripple=document.querySelector('#drag-ripple');const d=this.input.drag;if(d){ripple.style.left=`${d.x0}px`;ripple.style.top=`${d.y0}px`;ripple.classList.remove('hidden');}else ripple.classList.add('hidden');}
  frame(now){if(!this.running)return;const raw=Math.min(.1,(now-this.lastTime)/1000);this.lastTime=now;if(this.state&&!this.state.paused&&this.state.mode==='playing'){this.accumulator+=raw;let steps=0;let consumedTransient=false;let actions=this.input.sample(this.camYaw);while(this.accumulator>=TUNING.fixedDt&&steps<TUNING.maxDebtSteps){this.step(TUNING.fixedDt,actions);if(!consumedTransient){this.input.consumeTransient();consumedTransient=true;}actions={...actions,jump:false,switchCat:false,pause:false};this.accumulator-=TUNING.fixedDt;steps++;}if(steps===TUNING.maxDebtSteps&&this.accumulator>=TUNING.fixedDt)this.accumulator=0;this.syncModels(raw);this.updateCamera(raw);this.updateHUD();this.updateHenleyIndicator();}else if(this.state){this.syncModels(raw);}this.view.update(now/1000,raw);this.view.render();this.updateQA();requestAnimationFrame(this.frame);}
  updateQA(){if(!window.__PAWS_QA__)return;window.__PAWS_QA__.mode=this.state?.mode||'menu';window.__PAWS_QA__.paused=!!this.state?.paused;window.__PAWS_QA__.errors=this.qaErrors;window.__PAWS_QA__.drawCalls=this.view.renderer.info.render.calls;}
  installQA(){const q=new URLSearchParams(location.search).has('qa');window.__PAWS_QA__={mode:'menu',paused:false,errors:this.qaErrors,drawCalls:0,build:BUILD};window.__PAWS_GAME__={snapshot:()=>this.state?snapshotRun(this.state):null,pause:()=>this.pause('player'),resume:()=>this.resume(),restart:()=>this.restart(),teleportToObjective:()=>{if(!this.state)return;const o=this.level.objectives[this.state.objectiveIndex];if(o){const c=this.state.cats[this.state.activeCat];c.x=o.x;c.z=o.z;c.y=0;}},selectObjectiveCat:()=>{if(!this.state)return;const o=this.level.objectives[this.state.objectiveIndex];const idx=this.state.cats.findIndex(c=>c.name===o?.cat);if(idx>=0&&!this.state.cats[idx].captured)this.state.activeCat=idx;},placeHenleyNear:(distance=.55)=>{if(!this.state)return;const c=this.state.cats[this.state.activeCat],h=this.state.henley;h.x=c.x+distance;h.z=c.z;h.state='pounce';h.target=this.state.activeCat;h.lockedHeading=Math.atan2(c.x-h.x,c.z-h.z);h.timer=.35;h.catchTimer=0;},completeRoute:()=>{if(!this.state)return;let guard=20;while(this.state.mode==='playing'&&guard--){const o=this.level.objectives[this.state.objectiveIndex];const idx=this.state.cats.findIndex(c=>c.name===o.cat);this.state.activeCat=idx;this.state.cats[idx].x=o.x;this.state.cats[idx].z=o.z;stepRun(this.state,this.level,this.world,{steerDirection:{x:0,z:0},steerMagnitude:0,jump:false,switchCat:false},TUNING.fixedDt,this.callbacks());}},setModeSnapshot:()=>this.updateQA()};window.addEventListener('error',e=>this.qaErrors.push(`error:${e.message}`));window.addEventListener('unhandledrejection',e=>this.qaErrors.push(`rejection:${e.reason?.message||e.reason}`));if(q){const btn=document.querySelector('#qa-indicator'),panel=document.querySelector('#qa-panel');btn.classList.remove('hidden');btn.onclick=()=>{panel.classList.toggle('hidden');panel.textContent=JSON.stringify({qa:window.__PAWS_QA__,state:this.state?snapshotRun(this.state):null},null,2);};}}
}
function angleBlend(a,b,t){return a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*t;}
