import * as THREE from 'three';
import { BUILD, clamp, damp, slewAngle } from './config.js';
import { getLevel, assembleLevel } from './levels.js';
import { HenleyInput } from './henley-input.js';
import { AudioBus } from './audio.js';
import { loadCharacter } from './models.js';
import { SceneView } from './scene.js';
import { createStorybookHenley } from './henley-character.js';

const FIXED_DT=1/50,MAX_STEPS=5,HENLEY_SPEED=3.55,HENLEY_ACCEL=10.8,HENLEY_DECEL=13.8,HENLEY_TURN=8.6;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
function pointRectDistance(x,z,c){const dx=Math.max(Math.abs(x-c.x)-c.w/2,0),dz=Math.max(Math.abs(z-c.z)-c.d/2,0);return Math.hypot(dx,dz);}
function isFree(world,x,z,r=.30){return x>=world.bounds.minX+r&&x<=world.bounds.maxX-r&&z>=world.bounds.minZ+r&&z<=world.bounds.maxZ-r&&!world.colliders.some(c=>pointRectDistance(x,z,c)<r);}
function resolveMove(actor,world,dx,dz,r=.30){const nx=clamp(actor.x+dx,world.bounds.minX+r,world.bounds.maxX-r);if(isFree(world,nx,actor.z,r))actor.x=nx;else actor.vx*=.18;const nz=clamp(actor.z+dz,world.bounds.minZ+r,world.bounds.maxZ-r);if(isFree(world,actor.x,nz,r))actor.z=nz;else actor.vz*=.18;}
function rugRect(world){const rug=world.pieces.find(p=>p.kind==='rug');return rug||{x:0,z:3.8,w:3.8,d:2.1};}
function inRug(cat,rug){return Math.abs(cat.x-rug.x)<=rug.w*.5-.18&&Math.abs(cat.z-rug.z)<=rug.d*.5-.18;}
function storybookState(world){const rug=rugRect(world);return{mode:'playing',paused:false,elapsed:0,timeLeft:62,score:0,stage:'toy',toy:{x:3.35,z:-.35,picked:false},rug,henley:{x:0,z:-4.15,y:0,vx:0,vz:0,heading:0},cats:[{name:'orange',x:-2.6,z:.75,vx:0,vz:0,heading:0,followTimer:0,settled:false,wanderTimer:.7,targetX:-1.4,targetZ:1.7},{name:'gray',x:2.5,z:1.3,vx:0,vz:0,heading:Math.PI,followTimer:0,settled:false,wanderTimer:1.6,targetX:3.1,targetZ:2.5}],petsReady:0,callCount:0,onboarding:{phase:'move',startX:0,startZ:-4.15,time:0},lastInteraction:'',successStars:0};}

export class HenleyGame{
  constructor(canvas,ui){this.canvas=canvas;this.ui=ui;this.view=new SceneView(canvas);this.audio=new AudioBus();this.input=new HenleyInput(canvas);this.level=getLevel('ch1-l1');this.world=null;this.state=null;this.catModels=[];this.henleyModel=createStorybookHenley();this.view.scene.add(this.henleyModel.group);this.henleyModel.group.visible=false;this.camYaw=0;this.accumulator=0;this.lastTime=performance.now();this.running=true;this.qaErrors=[];this.modelReady=false;this.modelsPromise=this.loadModels();this.bindUI();this.installQA();this.ui.showTitle();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);addEventListener('resize',()=>this.onResize());}
  bindUI(){this.ui.on('play',()=>this.start());this.ui.on('resume',()=>this.resume());this.ui.on('restart',()=>this.restart());this.ui.on('home',()=>this.home());document.querySelector('#pause-button').onclick=()=>this.pause();}
  async loadModels(){const err=label=>e=>this.qaErrors.push(`model:${label}:${e?.message||e}`);const [orange,gray]=await Promise.all([loadCharacter('/assets/models/cat-orange.gltf',{placeholderColor:0xff7a22,onError:err('orange')}),loadCharacter('/assets/models/cat-gray.gltf',{placeholderColor:0x92a4b5,onError:err('gray')})]);this.catModels=[orange,gray];for(const m of this.catModels){m.group.visible=false;this.view.scene.add(m.group);}this.modelReady=true;}
  async start(){await Promise.all([this.modelsPromise,this.view.ready]);await this.audio.unlock().catch(()=>{});await this.audio.preload().catch(error=>this.qaErrors.push(`audio:${error?.message||error}`));this.input.resetTransient();this.world=assembleLevel(this.level);this.world.collectibles=[];this.state=storybookState(this.world);this.view.build(this.level,this.world);this.henleyModel.group.visible=true;this.henleyModel.setHoldingToy(false);for(const m of this.catModels){m.group.visible=true;m.resetMotion?.();}this.camYaw=0;this.syncModels(0);this.updateCamera(0,{snap:true});this.view.setObjective({x:this.state.toy.x,z:this.state.toy.z,cat:'orange'});this.ui.startHUD();this.ui.showGuidance('steer','Drag to move');this.audio.startBed?.();this.updateHUD();}
  home(){this.audio.stopAll();this.state=null;this.world=null;this.henleyModel.group.visible=false;for(const m of this.catModels)m.group.visible=false;this.view.setObjective(null);this.ui.showTitle();}
  restart(){this.audio.stopAll();this.start();}
  pause(){if(!this.state||this.state.mode!=='playing'||this.state.paused)return;this.state.paused=true;this.ui.setPause(true);}
  resume(){if(!this.state)return;this.input.resetTransient();this.state.paused=false;this.lastTime=performance.now();this.accumulator=0;this.ui.setPause(false);}
  onResize(){this.view.resize();if(this.state?.mode==='playing'&&!this.state.paused&&matchMedia('(pointer:coarse)').matches)this.pause();}
  callCats(){if(!this.state?.toy.picked)return false;for(const cat of this.state.cats)if(!cat.settled)cat.followTimer=5.4;this.state.callCount++;this.henleyModel.play('call');this.audio.play('switch',{volume:.18,rate:1.12});this.audio.maybeCat?.('objective');this.ui.toast('Orange! Gray! This way!',1000);return true;}
  interact(){const s=this.state;if(!s||s.mode!=='playing')return;if(!s.toy.picked){if(dist(s.henley,s.toy)<=.95){s.toy.picked=true;s.stage='roundup';s.score+=150;s.lastInteraction='toy';this.henleyModel.setHoldingToy(true);this.henleyModel.play('call');this.audio.play('objective',{volume:.28});this.ui.toast('Toy found · call the cats!',1300);for(const cat of s.cats)cat.followTimer=6.4;this.view.setObjective({x:s.rug.x,z:s.rug.z,cat:'gray'});if(s.onboarding)s.onboarding.phase='call';}else this.ui.toast('Move closer to the toy box',800);}else this.callCats();}
  updateHenley(actions,dt){const h=this.state.henley,has=actions.steerMagnitude>.025&&Math.hypot(actions.steerDirection.x,actions.steerDirection.z)>.15,targetSpeed=has?HENLEY_SPEED*actions.steerMagnitude:0;let tx=0,tz=0;if(has){const l=Math.hypot(actions.steerDirection.x,actions.steerDirection.z)||1;tx=actions.steerDirection.x/l*targetSpeed;tz=actions.steerDirection.z/l*targetSpeed;const targetHeading=Math.atan2(tx,tz);h.heading+=clamp(Math.atan2(Math.sin(targetHeading-h.heading),Math.cos(targetHeading-h.heading)),-HENLEY_TURN*dt,HENLEY_TURN*dt);}const accel=targetSpeed>Math.hypot(h.vx,h.vz)?HENLEY_ACCEL:HENLEY_DECEL;h.vx=damp(h.vx,tx,accel,dt);h.vz=damp(h.vz,tz,accel,dt);resolveMove(h,this.world,h.vx*dt,h.vz*dt,.31);}
  chooseWander(cat,index){const s=this.state;cat.wanderTimer=1.5+((Math.sin(s.elapsed*1.7+index*2.1)+1)*.65);const angle=s.elapsed*(.73+index*.11)+index*2.4,radius=1.5+((Math.cos(s.elapsed*.9+index)+1)*.65);let x=cat.x+Math.sin(angle)*radius,z=cat.z+Math.cos(angle)*radius;x=clamp(x,this.world.bounds.minX+.45,this.world.bounds.maxX-.45);z=clamp(z,this.world.bounds.minZ+.45,this.world.bounds.maxZ-.45);if(!isFree(this.world,x,z,.28)){x=index===0?-2.3:2.3;z=2.0+index*.7;}cat.targetX=x;cat.targetZ=z;}
  updateCats(dt){const s=this.state,h=s.henley;for(let i=0;i<s.cats.length;i++){const cat=s.cats[i];if(cat.settled){cat.vx=damp(cat.vx,0,12,dt);cat.vz=damp(cat.vz,0,12,dt);continue;}cat.followTimer=Math.max(0,cat.followTimer-dt);cat.wanderTimer-=dt;let tx,tz,speed;if(cat.followTimer>0){const side=i===0?-1:1;tx=h.x+side*.62;tz=h.z-.46;speed=2.75;}else{if(cat.wanderTimer<=0)this.chooseWander(cat,i);tx=cat.targetX;tz=cat.targetZ;speed=1.45;}const dx=tx-cat.x,dz=tz-cat.z,l=Math.hypot(dx,dz);if(l>.24){const desired=Math.min(speed,l*2.0),vx=dx/l*desired,vz=dz/l*desired;cat.vx=damp(cat.vx,vx,7.5,dt);cat.vz=damp(cat.vz,vz,7.5,dt);const targetHeading=Math.atan2(cat.vx,cat.vz);cat.heading+=clamp(Math.atan2(Math.sin(targetHeading-cat.heading),Math.cos(targetHeading-cat.heading)),-7*dt,7*dt);resolveMove(cat,this.world,cat.vx*dt,cat.vz*dt,.28);}else{cat.vx=damp(cat.vx,0,9,dt);cat.vz=damp(cat.vz,0,9,dt);}
      if(s.toy.picked&&inRug(cat,s.rug)&&dist(h,{x:s.rug.x,z:s.rug.z})<3.4){cat.settled=true;cat.followTimer=0;s.petsReady=s.cats.filter(c=>c.settled).length;s.score+=175;this.audio.play('collect',{volume:.22});this.audio.maybeCat?.('objective');this.ui.toast(`${cat.name==='orange'?'Orange':'Gray'} is on the rug`,1050);}
    }
  }
  updateOnboarding(dt){const s=this.state,ob=s?.onboarding;if(!ob)return;ob.time+=dt;if(ob.phase==='move'){if(dist(s.henley,{x:ob.startX,z:ob.startZ})>.65||ob.time>3.5){ob.phase='toy';ob.time=0;this.ui.showGuidance('interact','Find the toy box · tap nearby');}}else if(ob.phase==='toy'){if(s.toy.picked){ob.phase='call';ob.time=0;this.ui.showGuidance('call','Tap anywhere to call the cats');}}else if(ob.phase==='call'){if(s.callCount>0||ob.time>4){s.onboarding=null;this.ui.hideGuidance();}}}
  step(dt,actions){const s=this.state;if(!s||s.mode!=='playing')return;if(actions.pause){this.pause();return;}s.elapsed+=dt;s.timeLeft=Math.max(0,62-s.elapsed);this.updateHenley(actions,dt);this.updateCats(dt);this.updateOnboarding(dt);if(actions.interact)this.interact();if(s.toy.picked&&s.cats.every(c=>c.settled)){s.mode='success';s.successStars=3;s.score+=Math.round(s.timeLeft*12)+350;this.audio.stopBed?.();this.audio.play('success',{volume:.32});this.henleyModel.play('celebrate');for(const m of this.catModels)m.play('success',{loop:false,hold:2});setTimeout(()=>this.ui.showSuccess({score:s.score,elapsed:s.elapsed}),260);}else if(s.timeLeft<=0){s.mode='timeout';this.audio.stopBed?.();this.audio.play('caught',{volume:.22,rate:.9});setTimeout(()=>this.ui.showTimeout({score:s.score}),180);}}
  syncModels(dt){if(!this.state||!this.modelReady)return;const s=this.state,h=s.henley;this.henleyModel.group.position.set(h.x,0,h.z);this.henleyModel.group.rotation.y=h.heading;this.henleyModel.update(dt,{speed:Math.hypot(h.vx,h.vz)});for(let i=0;i<2;i++){const c=s.cats[i],m=this.catModels[i];m.group.position.set(c.x,0,c.z);m.group.rotation.y=c.heading+Math.PI;const speed=Math.hypot(c.vx,c.vz);const motion=m.selectMotion({speed,heading:c.heading,grounded:true,vy:0,vaultAnim:0,landTimer:0,mode:s.mode==='success'?'success':'playing',active:false,dt});m.play(c.settled?'idle':motion.anim,{loop:true,timeScale:c.followTimer>0?1.05:.78});m.update(dt);}}
  updateCamera(dt,{snap=false}={}){if(!this.state)return;const camera=this.view.camera,h=this.state.henley,portrait=camera.aspect<.82,targetYaw=h.heading;this.camYaw=snap?targetYaw:slewAngle(this.camYaw,targetYaw,(Math.PI/1.7)*dt);const targetFov=portrait?51:47;if(Math.abs(camera.fov-targetFov)>.01){camera.fov=snap?targetFov:damp(camera.fov,targetFov,5,dt);camera.updateProjectionMatrix();}const distBack=portrait?6.2:5.25,height=portrait?3.65:3.15,fx=Math.sin(this.camYaw),fz=Math.cos(this.camYaw),focusX=h.x,focusZ=h.z,desired={x:focusX-fx*distBack,y:height,z:focusZ-fz*distBack};if(snap)camera.position.set(desired.x,desired.y,desired.z);else{camera.position.x=damp(camera.position.x,desired.x,7.2,dt);camera.position.y=damp(camera.position.y,desired.y,7.2,dt);camera.position.z=damp(camera.position.z,desired.z,7.2,dt);}camera.lookAt(focusX+fx*.85,1.0,focusZ+fz*.85);}
  objectiveText(){const s=this.state;if(!s)return'';if(!s.toy.picked)return dist(s.henley,s.toy)<1.05?'Tap to pick up the pet toy':'Find the pet toy';if(s.petsReady===0)return'Lead both cats to the sunny rug';if(s.petsReady===1)return'Bring the other cat to the rug';return'Roundup complete';}
  updateHUD(){if(!this.state)return;const s=this.state;this.ui.updateHUD({objective:this.objectiveText(),timeLeft:s.timeLeft,score:s.score,petsReady:s.petsReady,toy:s.toy.picked});const ripple=document.querySelector('#drag-ripple'),d=this.input.drag;if(d){ripple.style.left=`${d.x0}px`;ripple.style.top=`${d.y0}px`;ripple.classList.remove('hidden');}else ripple.classList.add('hidden');}
  snapshot(){if(!this.state)return null;const s=this.state;return{mode:s.mode,paused:s.paused,elapsed:s.elapsed,timeLeft:s.timeLeft,score:s.score,stage:s.stage,petsReady:s.petsReady,toyPicked:s.toy.picked,henley:{...s.henley},cats:s.cats.map(c=>({...c})),callCount:s.callCount,onboarding:s.onboarding?{...s.onboarding}:null};}
  frame(now){if(!this.running)return;const raw=Math.min(.1,(now-this.lastTime)/1000);this.lastTime=now;if(this.state&&!this.state.paused&&this.state.mode==='playing'){this.accumulator+=raw;let steps=0,consumed=false,actions=this.input.sample(this.camYaw);while(this.accumulator>=FIXED_DT&&steps<MAX_STEPS){this.step(FIXED_DT,actions);if(!consumed){this.input.consumeTransient();consumed=true;}actions={...actions,interact:false,pause:false};this.accumulator-=FIXED_DT;steps++;}if(steps===MAX_STEPS&&this.accumulator>=FIXED_DT)this.accumulator=0;this.syncModels(raw);this.updateCamera(raw);this.updateHUD();}else if(this.state)this.syncModels(raw);this.view.update(now/1000,raw);this.view.render();this.updateQA();requestAnimationFrame(this.frame);}
  updateQA(){if(!window.__PAWS_QA__)return;window.__PAWS_QA__.mode=this.state?.mode||'menu';window.__PAWS_QA__.paused=!!this.state?.paused;window.__PAWS_QA__.errors=[...this.qaErrors];window.__PAWS_QA__.drawCalls=this.view.renderer.info.render.calls;}
  installQA(){window.__PAWS_QA__={mode:'menu',paused:false,errors:this.qaErrors,drawCalls:0,build:BUILD};window.__PAWS_GAME__={snapshot:()=>this.snapshot(),pause:()=>this.pause(),resume:()=>this.resume(),restart:()=>this.restart(),teleportHenleyToToy:()=>{if(!this.state)return false;this.state.henley.x=this.state.toy.x;this.state.henley.z=this.state.toy.z+.4;return true;},interact:()=>this.interact(),completeRoundup:()=>{if(!this.state)return false;this.state.toy.picked=true;this.henleyModel.setHoldingToy(true);for(const c of this.state.cats){c.x=this.state.rug.x+(c.name==='orange'?-.45:.45);c.z=this.state.rug.z;c.settled=true;}this.state.petsReady=2;return true;}};window.__HENLEY_QA__={get state(){return window.__PAWS_GAME__.snapshot();},get storybookCharacter(){return{visible:thisGame.henleyModel.group.visible,storybook:!!thisGame.henleyModel.storybook,holdingToy:thisGame.henleyModel.holdingToy,action:thisGame.henleyModel.action};}};const thisGame=this;window.addEventListener('error',e=>this.qaErrors.push(`error:${e.message}`));window.addEventListener('unhandledrejection',e=>this.qaErrors.push(`rejection:${e.reason?.message||e.reason}`));}
}
