import { BUILD } from './config.js';

export class HenleyUI{
  constructor(){this.root=document.querySelector('#screen-root');this.hud=document.querySelector('#hud');this.toastEl=document.querySelector('#toast');this.pauseBanner=document.querySelector('#pause-banner');this.build=document.querySelector('#build');this.guide=document.querySelector('#first-run-guide');this.guideText=document.querySelector('#first-run-guide-text');this.objectiveCard=document.querySelector('.hud .objective');this.handlers={};this.toastTimer=0;this.build.textContent=`${BUILD.version} · ${BUILD.revision}`;document.querySelector('#cat-dot')?.setAttribute('data-cat','henley');}
  on(name,fn){this.handlers[name]=fn;}
  emit(name,...args){this.handlers[name]?.(...args);}
  showTitle(){this.hideGuidance();this.hud.classList.add('hidden');this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen title-screen"><div class="eyebrow">A storybook pet-roundup game</div><h1>HENLEY<br><em>& THE PETS</em></h1><p>Help Henley round up Orange and Gray before the kitchen timer runs out.</p><div class="feature-row"><span>Drag to move</span><span>Tap to interact</span><span>Call the cats</span></div><div class="actions"><button class="btn primary" data-play>Kitchen Roundup</button><button class="btn secondary" data-how>How to play</button></div><small class="footnote">Storybook prototype · ${BUILD.version}</small></section>`;this.root.querySelector('[data-play]').onclick=()=>this.emit('play');this.root.querySelector('[data-how]').onclick=()=>this.showHow();}
  showHow(){this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen"><div class="eyebrow">Controls</div><h2>The screen is the controller.</h2><div class="how-grid"><article><b>Move</b><p>Drag anywhere to guide Henley through the room.</p></article><article><b>Interact</b><p>Tap when Henley is close to the pet toy.</p></article><article><b>Call</b><p>Once she has the toy, tap to call Orange and Gray toward her.</p></article><article><b>Round up</b><p>Lead both cats onto the sunny rug before time expires.</p></article></div><div class="actions"><button class="btn primary" data-start>Start</button><button class="btn secondary" data-back>Back</button></div></section>`;this.root.querySelector('[data-start]').onclick=()=>this.emit('play');this.root.querySelector('[data-back]').onclick=()=>this.showTitle();}
  startHUD(){this.root.classList.add('hidden');this.hud.classList.remove('hidden');this.setObjectiveVisible(true);}
  updateHUD({objective,timeLeft,score,petsReady,toy}){document.querySelector('#objective-name').textContent=objective||'Kitchen Roundup';document.querySelector('#objective-detail').textContent=`${Math.max(0,timeLeft).toFixed(1)}s · ${petsReady}/2 pets`;document.querySelector('#score').textContent=Math.round(score);document.querySelector('#combo').textContent=`${petsReady}/2 home`;document.querySelector('#stars').textContent=toy?'TOY ✓':'TOY ○';}
  setObjectiveVisible(v){this.objectiveCard?.classList.toggle('tutorial-hidden',!v);}
  showGuidance(kind,text='',position=null){if(!this.guide)return;this.guide.dataset.kind=kind;this.guideText.textContent=text;this.guide.classList.remove('hidden');if(position){this.guide.style.left=`${Math.max(54,Math.min(innerWidth-54,position.x))}px`;this.guide.style.top=`${Math.max(70,Math.min(innerHeight-80,position.y))}px`;}else{this.guide.style.left='';this.guide.style.top='';}}
  hideGuidance(){if(!this.guide)return;this.guide.classList.add('hidden');this.guide.dataset.kind='';this.guide.style.left='';this.guide.style.top='';this.guideText.textContent='';}
  setPause(paused){this.pauseBanner.classList.toggle('hidden',!paused);if(paused){this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen compact-screen"><div class="eyebrow">Paused</div><h2>Kitchen Roundup</h2><div class="actions"><button class="btn primary" data-resume>Resume</button><button class="btn secondary" data-restart>Restart</button></div></section>`;this.root.querySelector('[data-resume]').onclick=()=>this.emit('resume');this.root.querySelector('[data-restart]').onclick=()=>this.emit('restart');}else this.root.classList.add('hidden');}
  showSuccess({score,elapsed}){this.hideGuidance();this.hud.classList.add('hidden');this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen terminal success"><div class="eyebrow">Kitchen Roundup complete</div><h2>Everybody's together.</h2><div class="result-stars">★★★</div><div class="terminal-score">${Math.round(score)}</div><p>Henley found the toy and brought both cats to the sunny rug in ${elapsed.toFixed(1)}s.</p><div class="actions"><button class="btn primary" data-replay>Play again</button><button class="btn secondary" data-home>Home</button></div></section>`;this.root.querySelector('[data-replay]').onclick=()=>this.emit('restart');this.root.querySelector('[data-home]').onclick=()=>this.emit('home');}
  showTimeout({score}){this.hideGuidance();this.hud.classList.add('hidden');this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen terminal caught"><div class="eyebrow">Time's up</div><h2>The cats got distracted.</h2><div class="terminal-score">${Math.round(score)}</div><p>Grab the toy early, call them close, and lead them together toward the rug.</p><div class="actions"><button class="btn primary" data-retry>Try again</button><button class="btn secondary" data-home>Home</button></div></section>`;this.root.querySelector('[data-retry]').onclick=()=>this.emit('restart');this.root.querySelector('[data-home]').onclick=()=>this.emit('home');}
  toast(text,ms=1500){this.toastEl.textContent=text;this.toastEl.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.toastEl.classList.add('hidden'),ms);}
}
