import { BUILD, DIFFICULTIES } from './config.js';
import { chapterUnlockThreshold } from './levels.js';

export class GameUI{
  constructor(profile){this.profile=profile;this.root=document.querySelector('#screen-root');this.hud=document.querySelector('#hud');this.toastEl=document.querySelector('#toast');this.pauseBanner=document.querySelector('#pause-banner');this.build=document.querySelector('#build');this.guide=document.querySelector('#first-run-guide');this.guideText=document.querySelector('#first-run-guide-text');this.objectiveCard=document.querySelector('.hud .objective');this.build.textContent=`${BUILD.version} · ${BUILD.revision}`;this.toastTimer=0;this.handlers={};}
  on(name,fn){this.handlers[name]=fn;}
  emit(name,...args){this.handlers[name]?.(...args);}
  showTitle(){this.hideGuidance();this.hud.classList.add('hidden');this.root.innerHTML=`<section class="screen title-screen"><div class="eyebrow">A two-cat escape game</div><h1>PAWS<br><em>ON THE RUN</em></h1><p>Switch between Orange and Gray, finish the mischief route, and stay one paw ahead of Henley.</p><div class="feature-row"><span>Drag to run</span><span>Tap to jump</span><span>Tap the other cat to switch</span></div><div class="actions"><button class="btn primary" data-play>Play</button><button class="btn secondary" data-how>How to play</button></div><small class="footnote">${BUILD.version} · mobile-first Beta V2</small></section>`;this.root.classList.remove('hidden');this.root.querySelector('[data-play]').onclick=()=>this.emit('play');this.root.querySelector('[data-how]').onclick=()=>this.showHow();}
  showHow(){this.root.innerHTML=`<section class="screen"><div class="eyebrow">Controls</div><h2>The screen is the controller.</h2><div class="how-grid"><article><b>Run</b><p>Drag anywhere. Short drags walk; longer drags run.</p></article><article><b>Jump</b><p>Tap the floor. A buffered tap near a low edge helps vault.</p></article><article><b>Switch</b><p>Tap the other cat. Some objectives belong to a specific cat.</p></article><article><b>Escape</b><p>Complete every objective before Henley catches your active cat.</p></article></div><div class="actions"><button class="btn primary" data-back>Got it</button></div></section>`;this.root.querySelector('[data-back]').onclick=()=>this.showTitle();}
  showMap(levels){this.hideGuidance();const total=this.profile.totalStars(),threshold=chapterUnlockThreshold(1),unlocked=this.profile.data.unlockedSets.includes('sunroom')||total>=threshold;const cards=levels.map(l=>{const rec=this.profile.data.levels[l.id]||{};const locked=l.chapter===2&&!unlocked;const best=rec.bestScore?`Best ${rec.bestScore}${rec.bestTime?` · ${rec.bestTime.toFixed(1)}s`:''}`:'New route';return `<button class="level-card ${locked?'locked':''}" data-level="${l.id}" ${locked?'disabled':''}><span class="level-num">${l.chapter}.${l.id.split('l')[1]}</span><b>${l.name}</b><small>${l.theme==='kitchen'?'Kitchen':'Sunroom'} · ${l.parTime}s par</small><span class="mini-stars">${'★'.repeat(rec.stars||0)}${'☆'.repeat(3-(rec.stars||0))}</span><span class="best">${best}</span></button>`;}).join('');this.root.innerHTML=`<section class="screen map-screen"><header class="screen-head"><div><div class="eyebrow">Chapter map</div><h2>Choose an escape route</h2></div><div class="star-total">★ ${total}</div></header><div class="level-grid">${cards}</div><div class="chapter-lock ${unlocked?'unlocked':''}">${unlocked?'Sunroom unlocked':`Earn ${threshold} chapter stars to unlock the Sunroom`}</div><div class="actions"><button class="btn secondary" data-home>Back</button></div></section>`;this.root.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>this.emit('chooseLevel',b.dataset.level));this.root.querySelector('[data-home]').onclick=()=>this.showTitle();}
  showRunSetup(level){this.hideGuidance();const selected=this.profile.data.difficulty;const tiers=Object.entries(DIFFICULTIES).map(([id,t])=>`<button class="tier-card ${selected===id?'selected':''}" data-tier="${id}"><b>${t.label}</b><small>${id==='kitten'?'More breathing room':id==='cat'?'Balanced chase':'Tighter pursuit'}</small></button>`).join('');const cosmetic=this.profile.data.cosmetic;const chips=this.profile.data.unlockedCosmetics.map(id=>{const label=id==='classic'?'Classic':id==='teal'?'Teal':'Rust';const swatch=id==='classic'?'cream':id;return `<button class="chip ${cosmetic===id?'selected':''}" data-cosmetic="${id}"><i class="swatch ${swatch}"></i>${label}</button>`;}).join('');this.root.innerHTML=`<section class="screen setup-screen"><div class="eyebrow">${level.name}</div><h2>Pick the chase pressure</h2><div class="tier-grid">${tiers}</div><h3>Collar accent</h3><div class="cosmetic-grid">${chips}</div><p class="setup-note">${level.objectives.length} objectives · ${level.parTime}s par · target ${level.targetScore}</p><div class="actions"><button class="btn primary" data-start>Start run</button><button class="btn secondary" data-map>Map</button></div></section>`;this.root.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{this.profile.setDifficulty(b.dataset.tier);this.showRunSetup(level);});this.root.querySelectorAll('[data-cosmetic]').forEach(b=>b.onclick=()=>{this.profile.setCosmetic(b.dataset.cosmetic);this.showRunSetup(level);});this.root.querySelector('[data-start]').onclick=()=>this.emit('start',level);this.root.querySelector('[data-map]').onclick=()=>this.emit('map');}
  startHUD(){this.root.classList.add('hidden');this.hud.classList.remove('hidden');this.setObjectiveVisible(true);this.setObjectiveHeld(false);}
  updateHUD({objective,timeLeft,score,combo,stars}){document.querySelector('#objective-name').textContent=objective?.label||'Escape';document.querySelector('#objective-detail').textContent=objective?`${objective.cat==='orange'?'Orange':'Gray'} · ${Math.max(0,timeLeft).toFixed(1)}s`:'Route complete';document.querySelector('#cat-dot').dataset.cat=objective?.cat||'orange';document.querySelector('#score').textContent=Math.round(score);document.querySelector('#combo').textContent=`x${combo} combo`;document.querySelector('#stars').textContent=`${'★'.repeat(stars)}${'☆'.repeat(3-stars)}`;}
  setObjectiveVisible(visible){this.objectiveCard?.classList.toggle('tutorial-hidden',!visible);}
  setObjectiveHeld(held){this.objectiveCard?.classList.toggle('timer-held',!!held);}
  showGuidance(kind,text='',position=null){if(!this.guide)return;this.guide.dataset.kind=kind;this.guideText.textContent=text;this.guide.classList.remove('hidden');if(position)this.positionGuidance(position.x,position.y);else{this.guide.style.left='';this.guide.style.top='';}}
  positionGuidance(x,y){if(!this.guide)return;this.guide.style.left=`${Math.max(54,Math.min(innerWidth-54,x))}px`;this.guide.style.top=`${Math.max(70,Math.min(innerHeight-80,y))}px`;}
  hideGuidance(kind=null){if(!this.guide)return;if(kind&&this.guide.dataset.kind!==kind)return;this.guide.classList.add('hidden');this.guide.dataset.kind='';this.guide.style.left='';this.guide.style.top='';this.guideText.textContent='';}
  setPause(paused,{reason='player',resumeOnly=false}={}){this.pauseBanner.classList.toggle('hidden',!paused);document.querySelector('#pause-reason').textContent=reason==='rotation'?'Orientation changed. Resume when ready.':'The chase is frozen.';if(paused){this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen compact-screen"><div class="eyebrow">Paused</div><h2>Catch your breath.</h2><div class="actions"><button class="btn primary" data-resume>Resume</button>${resumeOnly?'':'<button class="btn secondary" data-restart>Restart run</button>'}</div></section>`;this.root.querySelector('[data-resume]').onclick=()=>this.emit('resume');if(!resumeOnly)this.root.querySelector('[data-restart]').onclick=()=>this.emit('restart');}else this.root.classList.add('hidden');}
  showCaught({score}){this.hideGuidance();this.hud.classList.add('hidden');this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen terminal caught"><div class="eyebrow">Henley caught up</div><h2>Caught!</h2><div class="terminal-score">${Math.round(score)}</div><p>Good run. Switch cats earlier or cut a tighter line around the furniture.</p><div class="actions"><button class="btn primary" data-retry>Retry</button><button class="btn secondary" data-exit>Map</button></div></section>`;this.root.querySelector('[data-retry]').onclick=()=>this.emit('retry');this.root.querySelector('[data-exit]').onclick=()=>this.emit('map');}
  showResults({level,score,stars,pillars,elapsed}){this.hideGuidance();this.hud.classList.add('hidden');this.root.classList.remove('hidden');this.root.innerHTML=`<section class="screen terminal success"><div class="eyebrow">Route escaped</div><h2>${level.name} complete</h2><div class="result-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><div class="terminal-score">${Math.round(score)}</div><div class="pillar-grid"><div><span>Mischief</span><b>${pillars.objective}</b></div><div><span>Collect</span><b>${pillars.collectible}</b></div><div><span>Evasion</span><b>${pillars.evasion}</b></div><div><span>Tag team</span><b>${pillars.switch}</b></div></div><p>${elapsed.toFixed(1)}s · par ${level.parTime}s</p><div class="actions"><button class="btn primary" data-replay>Replay</button><button class="btn secondary" data-exit>Map</button></div></section>`;this.root.querySelector('[data-replay]').onclick=()=>this.emit('retry');this.root.querySelector('[data-exit]').onclick=()=>this.emit('map');}
  toast(text,ms=1700){this.toastEl.textContent=text;this.toastEl.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.toastEl.classList.add('hidden'),ms);}
}